<!-- 
This Component wasn't used since for some reason, 
using it and x-slots for the pages exceeded the xampp memory limit.
Layouts were also considered but the small size of this project made it unnnecessary.
-->
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{$title}}</title>
</head>
<body>
    <nav class="navbar">
        <a href="/">Home</a>
        <a href="collection">Cat Collection</a>
        <a href="map">Map</a>
    </nav>

    {{$content}}
    
    <footer class="footer">
        <p>Copyright &copy; of S.J.C. 2024. All images generated by Bing AI Image Creator.</p>
    </footer>
</body>
</html>
<!--
Below is the Basic Corresponding Code

<x-nav_layout>   
    
    <x-slot name="title"></x-slot>

    <x-slot name="content">

    </x-slot name="content">

</x-nav_layout>
    
    !>