<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="/css/home-style.css">
    <title>Cat Tracker Cafe</title>
</head>
<body>
    <nav class="navbar">
        <a href="/">Home</a>
        <a href="collection">Cat Collection</a>
        <a href="map">Map</a>
    </nav>
    <header class="hero">
        <div class="content-box">
            <h1 class="welcome-text">Welcome to Cat Tracker Cafe</h1>
            <p class="intro-text">
                We understand that keeping track of multiple cats can be a daunting task.
                We’re glad to hear that you’re using the “Cat Tracker Cafe” app to help you manage your feline friends.
                The app provides a convenient way to keep track of your cats’ whereabouts and update their information.
                You can easily update your collection of cats by visiting the collection page.
                Additionally, the map page allows you to see your cats’ locations in real-time.
                This feature can be especially helpful if you have outdoor cats and want to keep an eye on them.
                We hope you find the app useful and that it helps you keep your cats safe and happy! 😺
            </p>
        </div>
    </header>

    <footer class="footer">
        <p>Copyright &copy; of S.J.C. 2024. All images generated by Bing AI Image Creator.</p>
    </footer>
</body>
</html>
