<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="/css/home-style.css">
    <title>Cat Tracker Map</title>
</head>
<body>
    <nav class="navbar">
        <a href="/">Home</a>
        <a href="collection">Cat Collection</a>
        <a href="map">Map</a>
    </nav>
     <footer class="footer">
        <p>Copyright &copy; of S.J.C. 2024. All images generated by Bing AI Image Creator.</p>
    </footer>
</body>
</html> 